import './globals.css'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {

const handleNavigateHome = () => {
    router.push('/');
  };
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>


    </html>
  )
}
